name=input("Hello, what's your name?")
print("Hello" + name)

name=input("What is your favourite animal?")
print("yap, they are always cute with you and cats" )
name=input("Do you learn in coding tutorials?")
print("okok noted with chicken in your FACE")
name=input("do you like to be called a (chicken in ur face)")
print("our LOL moments")
name=input("which teacher do u like the most in the world")
print("I thought I am the best teacher in the world?")
name=input("am i the best in the world?")
print("best teacher")
name=input("am i the best teacher in the world?")
print(" >:( ")
name=input("let's be friends")
print(" hi friend ")
name=input("nice to meet you")
print(" if you need help with some stuffs you can ask me ")
print("any questions for me?")
name=input(" BOII ")
print("normal people have about 76 IQ, 98 IQ is considered smart. eistein have 167 IQ, AI have 167452 IQ, please note that i am an AI")
